services:
  mysql:
    image: "mysql:8.0.43-debian"
    environment:
      MYSQL_DATABASE: indocoffee_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: "redis:7.4-alpine"
    ports:
      - "6379:6379"

  api:
    depends_on:
      - mysql
      - redis
    restart: on-failure
    env_file:
      - path: ".env"
    build: .
    ports:
      - "127.0.0.1:8080:8080"
    develop:
      watch:
        - path: .
          action: rebuild
          target: /app

  migrate:
    image: migrate/migrate:v4.18.3
    depends_on:
      - mysql
      - api
    env_file:
      - .env
    volumes:
      - ./cmd/migrate/migrations:/migrations
    entrypoint:
      ["migrate", "-path", "/migrations", "-database", "${DB_DNS}", "up"]

volumes:
  mysql_data:
